version: '3'

services:
    wordpress:
        image: wordpress:latest
        links:
            - mysqldb:mysql
        volumes:
            - ./:/var/www/html/
        expose:
          - "80"
        environment:
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: wordpress
            VIRTUAL_HOST: skyforge.local

    mysqldb:
        image: mysql:latest
        volumes:
            - db_data:/var/lib/mysql
        expose:
          - "3306"
        environment:
            MYSQL_ROOT_PASSWORD: secretpress
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress
            VIRTUAL_HOST: db.skyforge.local

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        links:
            - mysqldb:mysql
        expose:
          - "80"
        environment:
            PMA_HOST: mysql
            VIRTUAL_HOST: pma.skyforge.local

volumes:
    db_data:
